### ISSUE TITLE
Update for Elm 0.15

### ISSUE THREAD

**Issue by wyleyr** [Dandandan/parser#10]
I've just (re-)installed Elm, and I'd like to use this library in a new project.  Elm 0.15, the version I installed, was apparently released very recently and introduces some changes that prevent the Parser library from being installed via elm-package.  There are at least two things I've run into that need to be fixed:

1. Add an "elm-version" declaration in elm-package.json
2. Use the new import syntax: "import Mod (..)" should become "import Mod exposing (..)"

The dependencies probably also need to be updated.

**Comment by Dandandan** [comment]
I updated the library. There seems to be a problem with building elm-check from @TheSeamau5.

**Comment by TheSeamau5** [comment]
Sorry for the issues. `elm-check` has been updated but the update has brought about some breaking changes. The reason for the breaking changes is because I've added : 

1. shrinking
2. `elm-test` integration
3. the ability to group tests into suites
4. a new clearer terminology (claims vs properties)
5. an optional DSL for improved readibility
6. the ability to have expected vs actual results instead of just defining a property that returns a bool. 

Concretely, this current test of yours: 

```elm
property "Natural parsing "
            (\number ->
                parse PN.natural (toString number) == Ok number
            ) (int 0 1000000)
```

would look something like this:

```elm
claim_parsing_number = 
  claim
    "Parsing a number converted to a string will yield the original number"
  `that`
    (\number -> parse PN.natural (toString number))
  `is`
    (\number -> Ok number)
  `for`
    int
```

Or more compactly:

```elm
claim_parsing_number = 
  claim
    "Parsing a number converted to a string will yield the original number"
  `that`
    toString >> parse PN.natural
  `is`
    Ok
  `for`
    int
```

(note, the DSL is optional, just remove the infix functions and it works fine)

The advantage here is that you'll see an expected vs actual result if there's a bug, not just the failing input. So, if you expected to get `10` but got `1` for example, you'll see something that says "expected : 10, actual : 1".

Here's an example of how these errors look like when fully expanded:

![screen shot 2015-05-05 at 3 58 46 am](https://cloud.githubusercontent.com/assets/3227869/7569697/674833c8-f802-11e4-8df3-6fc92bc86953.png)

Also, you get shrinking, which means that if random generation finds that there's a problem in parsing "8778710", but in reality even "10" fails, it will shrink that big input until it gets to the smallest input that still fails (and thus reduce it to "10" or smaller). And, I'm sure you'll agree that it's easier to see what's wrong with "10" than with "8778710".


I recommend holding off slightly for a moment because I've realized that shrinking has added some boilerplate to your tests .Since shrinking strategies can't be `mapped` or `flatmapped` you have to write your own for your own types. I tried to make it straightforward to do so, but it is still a lot of boilerplate. I've then seen that Clojure's `test.check` do this trick where they're allow you to have all these fun functional combinators while preserving shrinking, so I'm integrating that solution into `elm-check` and then hopefully, the only thing you'll need to change in your tests is the word `property` to `claim`. I figured out a way how to integrate these changes without really breaking the external API, but since the types will change, it'll be a major version change. 


Finally, I removed temporarily continuous checking. The reason for this is cuz the previous version was Signal-based and that could have terrible performance problems. The next version will be task based and will hopefully be interactive (like, you can click to add more tests, get reports as JSON, etc...). It's quite an undertaking, so that'll take time. In the mean-time, the best bet will be to use the `elm-test` integration because you get all the awesomeness of shrinking and property-based testing, but instead, you're generating unit tests and folks have already figured out CI integration with `elm-test` (so, yes, you can have that sticker on github). 

You can read more about the new features of `elm-check` at the repo: https://github.com/TheSeamau5/elm-check

or at the mailing list thread: https://groups.google.com/d/msg/elm-discuss/3SbDOaxvWJg/gG9dNdL71e0J

or follow the progress for the simplified update at this issue: 
https://github.com/TheSeamau5/elm-check/issues/10

Again, I'm super sorry for the issues, but hopefully I'll make it up to you by providing a better testing framework.

**Comment by wyleyr** [comment]
Thanks for the update, Dandandan!

**Comment by Dandandan** [comment]
@TheSeamau5 thanks for the info. Will check soon ;).

@wyleyr You're welcome!
